"""Added new columms in orders table

Revision ID: c2db8a6b7e6f
Revises: 1fd25e1b562b
Create Date: 2023-12-13 14:00:43.005091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2db8a6b7e6f'
down_revision: Union[str, None] = '1fd25e1b562b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_date', sa.Date(), nullable=True))
    op.add_column('orders', sa.Column('total', sa.Integer(), nullable=True))
    op.alter_column('products', 'Expiry_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'Expiry_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)
    op.drop_column('orders', 'total')
    op.drop_column('orders', 'order_date')
    # ### end Alembic commands ###
